name: bomberbubi
description: he's a bubi with bombs
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  route: '>=0.4.0 <0.5.0'
